name: ECR Build and Push
on:
  push:
    branches: [ "main" ]

defaults:
  run:
    working-directory: ./App

env:
  AWS_REGION: eu-west-2
  ECR_REPOSITORY: ecr_app
  ECS_SERVICE: ecs_service
  ECS_CLUSTER: ecs_cluster

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: #${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: #${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: #${{ env.AWS_REGION }}
